import { Router } from "express";
import authRoutes from "./auth.routes";
import productRoutes from "./product.routes";
import userRoutes from "./user.routes";
import categoryRoutes from "./category.routes";
import collectionRoutes from "./collection.routes";
import inventoryRoutes from "./inventory.routes";
import uploadRoutes from "./upload.routes";
import orderRoutes from "./order.routes";
import customerRoutes from "./customer.routes";
import homeRoutes from "./home.routes";
import reviewRoutes from "./review.routes";
import couponRoutes from "./coupon.routes";
import ticketRoutes from "./ticket.routes";
import brandRoutes from "./brand.routes";
import attributeRoutes from "./attribute.routes";
import discountRoutes from "./discount.routes";
import marketingBannerRoutes from "./marketing-banner.routes";
import contactMessageRoutes from "./contact-message.routes";
import customerGroupRoutes from "./customer-group.routes";
import storeSettingsRoutes from "./store-settings.routes";
import adminUserRoutes from "./admin-user.routes";
import testimonialRoutes from "./testimonial.routes";
import homePromotionRoutes from "./home-promotion.routes";
import faqRoutes from "./faq.routes";
import staticPageRoutes from "./static-page.routes";
import newsletterRoutes from "./newsletter.routes";
import dashboardRoutes from "./dashboard.routes";
import reportRoutes from "./report.routes";

const router = Router();

router.get("/health", (_req, res) => res.json({ success: true, data: { status: "ok" } }));
router.use("/auth", authRoutes);
router.use("/products", productRoutes);
router.use("/users", userRoutes);
router.use("/categories", categoryRoutes);
router.use("/collections", collectionRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/uploads", uploadRoutes);
router.use("/orders", orderRoutes);
router.use("/customers", customerRoutes);
router.use("/home", homeRoutes);
router.use("/reviews", reviewRoutes);
router.use("/coupons", couponRoutes);
router.use("/tickets", ticketRoutes);
router.use("/brands", brandRoutes);
router.use("/attributes", attributeRoutes);
router.use("/discounts", discountRoutes);
router.use("/marketing-banners", marketingBannerRoutes);
router.use("/contact-messages", contactMessageRoutes);
router.use("/customer-groups", customerGroupRoutes);
router.use("/settings", storeSettingsRoutes);
router.use("/admin-users", adminUserRoutes);
router.use("/testimonials", testimonialRoutes);
router.use("/home-promotions", homePromotionRoutes);
router.use("/faqs", faqRoutes);
router.use("/static-pages", staticPageRoutes);
router.use("/newsletter-config", newsletterRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/reports", reportRoutes);

export default router;
