import { Product, ProductVariant } from '../models/product.model';
import { placeholderImage } from '../models/common.model';

function variants(sku: string, sizes: string[], colors: string[], price: number, stockPer = 12): ProductVariant[] {
  const out: ProductVariant[] = [];
  let i = 0;
  for (const color of colors) {
    for (const size of sizes) {
      i++;
      out.push({
        id: `${sku}-v${i}`,
        size,
        color,
        sku: `${sku}-${size}-${color.slice(0, 3).toUpperCase()}`,
        price,
        stock: stockPer,
      });
    }
  }
  return out;
}

function gallery(seed: string, count = 3): string[] {
  return Array.from({ length: count }, (_, i) => placeholderImage(`${seed}-g${i}`, 700, 900));
}

export const PRODUCTS_MOCK: Product[] = [
  {
    id: 'prod-001', name: 'Premium Oversized T-Shirt', sku: 'CLT-TSH-001',
    description: 'A heavyweight 240gsm cotton tee cut for an oversized, streetwear-first fit. Garment-dyed for a lived-in look that only gets better with wear.',
    shortDescription: 'Heavyweight oversized cotton tee.',
    brandId: 'brand-clotchy-originals', categoryId: 'cat-tshirts', collectionIds: ['col-streetwear', 'col-new-arrivals'],
    tags: ['oversized', 'cotton', 'streetwear'],
    price: 1499, salePrice: 1199, costPrice: 650, tax: 5, discount: 20,
    stock: 84, lowStockThreshold: 15, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-001', 700, 900), thumbnail: placeholderImage('prod-001-thumb', 200, 200), gallery: gallery('prod-001'),
    variants: variants('CLT-TSH-001', ['S', 'M', 'L', 'XL'], ['Black', 'White', 'Olive'], 1199),
    metaTitle: 'Premium Oversized T-Shirt | Clotchy', metaDescription: 'Shop the Premium Oversized T-Shirt in black, white and olive.',
    urlSlug: 'premium-oversized-t-shirt', keywords: 'oversized tee, streetwear t-shirt',
    status: 'published', featured: true, bestSeller: true, unitsSold: 412, revenue: 493788, rating: 4.6, reviewCount: 128,
    createdAt: '2026-01-12',
  },
  {
    id: 'prod-002', name: 'Classic Cotton Shirt', sku: 'CLT-SHT-002',
    description: 'A tailored, breathable cotton shirt for everyday formal wear. Wrinkle-resistant finish with mother-of-pearl buttons.',
    shortDescription: 'Tailored breathable cotton shirt.',
    brandId: 'brand-clotchy-originals', categoryId: 'cat-shirts', collectionIds: ['col-premium'],
    tags: ['formal', 'cotton', 'office'],
    price: 2199, salePrice: null, costPrice: 950, tax: 5, discount: 0,
    stock: 56, lowStockThreshold: 10, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-002', 700, 900), thumbnail: placeholderImage('prod-002-thumb', 200, 200), gallery: gallery('prod-002'),
    variants: variants('CLT-SHT-002', ['S', 'M', 'L', 'XL'], ['White', 'Blue'], 2199),
    metaTitle: 'Classic Cotton Shirt | Clotchy', metaDescription: 'Tailored classic cotton shirt for everyday wear.',
    urlSlug: 'classic-cotton-shirt', keywords: 'cotton shirt, formal shirt',
    status: 'published', featured: false, bestSeller: false, unitsSold: 187, revenue: 411213, rating: 4.4, reviewCount: 64,
    createdAt: '2026-01-18',
  },
  {
    id: 'prod-003', name: 'Relaxed Fit Jeans', sku: 'CLT-JNS-003',
    description: 'Stonewashed denim with a relaxed fit through the hip and thigh, tapering to the ankle. Reinforced stitching for daily durability.',
    shortDescription: 'Stonewashed relaxed-fit denim.',
    brandId: 'brand-denim-co', categoryId: 'cat-jeans', collectionIds: ['col-streetwear'],
    tags: ['denim', 'relaxed-fit'],
    price: 2999, salePrice: 2499, costPrice: 1300, tax: 5, discount: 17,
    stock: 12, lowStockThreshold: 15, availability: 'in-stock', allowBackorder: true,
    mainImage: placeholderImage('prod-003', 700, 900), thumbnail: placeholderImage('prod-003-thumb', 200, 200), gallery: gallery('prod-003'),
    variants: variants('CLT-JNS-003', ['30', '32', '34', '36'], ['Blue', 'Black'], 2499),
    metaTitle: 'Relaxed Fit Jeans | Clotchy', metaDescription: 'Stonewashed relaxed fit jeans.',
    urlSlug: 'relaxed-fit-jeans', keywords: 'jeans, denim',
    status: 'published', featured: true, bestSeller: true, unitsSold: 356, revenue: 889644, rating: 4.5, reviewCount: 97,
    createdAt: '2026-01-05',
  },
  {
    id: 'prod-004', name: 'Premium Hoodie', sku: 'CLT-HOD-004',
    description: 'A brushed-fleece hoodie with a dropped shoulder seam and kangaroo pocket. Ribbed cuffs and hem for a locked-in fit.',
    shortDescription: 'Brushed-fleece dropped-shoulder hoodie.',
    brandId: 'brand-urban-edge', categoryId: 'cat-hoodies', collectionIds: ['col-winter', 'col-trending'],
    tags: ['hoodie', 'fleece', 'winter'],
    price: 3299, salePrice: null, costPrice: 1500, tax: 5, discount: 0,
    stock: 63, lowStockThreshold: 15, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-004', 700, 900), thumbnail: placeholderImage('prod-004-thumb', 200, 200), gallery: gallery('prod-004'),
    variants: variants('CLT-HOD-004', ['S', 'M', 'L', 'XL', 'XXL'], ['Black', 'Grey'], 3299),
    metaTitle: 'Premium Hoodie | Clotchy', metaDescription: 'Brushed fleece premium hoodie.',
    urlSlug: 'premium-hoodie', keywords: 'hoodie, fleece hoodie',
    status: 'published', featured: true, bestSeller: true, unitsSold: 298, revenue: 983102, rating: 4.7, reviewCount: 145,
    createdAt: '2025-12-20',
  },
  {
    id: 'prod-005', name: 'Casual Bomber Jacket', sku: 'CLT-JKT-005',
    description: 'A lightweight bomber jacket with ribbed collar and cuffs, water-resistant shell, and internal zip pocket.',
    shortDescription: 'Lightweight water-resistant bomber.',
    brandId: 'brand-urban-edge', categoryId: 'cat-jackets', collectionIds: ['col-winter'],
    tags: ['jacket', 'bomber', 'outerwear'],
    price: 4499, salePrice: 3799, costPrice: 2100, tax: 5, discount: 15,
    stock: 8, lowStockThreshold: 10, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-005', 700, 900), thumbnail: placeholderImage('prod-005-thumb', 200, 200), gallery: gallery('prod-005'),
    variants: variants('CLT-JKT-005', ['S', 'M', 'L', 'XL'], ['Black', 'Olive'], 3799),
    metaTitle: 'Casual Bomber Jacket | Clotchy', metaDescription: 'Lightweight casual bomber jacket.',
    urlSlug: 'casual-bomber-jacket', keywords: 'bomber jacket, outerwear',
    status: 'published', featured: false, bestSeller: false, unitsSold: 74, revenue: 281126, rating: 4.3, reviewCount: 31,
    createdAt: '2026-02-02',
  },
  {
    id: 'prod-006', name: 'Designer Sweatshirt', sku: 'CLT-SWT-006',
    description: 'A crewneck sweatshirt in mid-weight loopback cotton, finished with a tonal embroidered logo at the chest.',
    shortDescription: 'Loopback cotton crewneck sweatshirt.',
    brandId: 'brand-noir-label', categoryId: 'cat-hoodies', collectionIds: ['col-premium', 'col-trending'],
    tags: ['sweatshirt', 'crewneck'],
    price: 2799, salePrice: null, costPrice: 1200, tax: 5, discount: 0,
    stock: 41, lowStockThreshold: 10, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-006', 700, 900), thumbnail: placeholderImage('prod-006-thumb', 200, 200), gallery: gallery('prod-006'),
    variants: variants('CLT-SWT-006', ['S', 'M', 'L', 'XL'], ['Beige', 'Black'], 2799),
    metaTitle: 'Designer Sweatshirt | Clotchy', metaDescription: 'Loopback cotton designer sweatshirt.',
    urlSlug: 'designer-sweatshirt', keywords: 'sweatshirt, crewneck',
    status: 'published', featured: false, bestSeller: true, unitsSold: 203, revenue: 568197, rating: 4.5, reviewCount: 58,
    createdAt: '2026-01-25',
  },
  {
    id: 'prod-007', name: 'Slim Fit Chino Trousers', sku: 'CLT-TRS-007',
    description: 'Stretch cotton chinos tailored to a slim leg with a flat front and hidden coin pocket.',
    shortDescription: 'Stretch cotton slim chinos.',
    brandId: 'brand-clotchy-originals', categoryId: 'cat-jeans', collectionIds: ['col-summer'],
    tags: ['chino', 'trousers'],
    price: 2399, salePrice: 1999, costPrice: 1050, tax: 5, discount: 17,
    stock: 5, lowStockThreshold: 10, availability: 'in-stock', allowBackorder: true,
    mainImage: placeholderImage('prod-007', 700, 900), thumbnail: placeholderImage('prod-007-thumb', 200, 200), gallery: gallery('prod-007'),
    variants: variants('CLT-TRS-007', ['30', '32', '34'], ['Beige', 'Grey'], 1999),
    metaTitle: 'Slim Fit Chino Trousers | Clotchy', metaDescription: 'Stretch cotton slim chino trousers.',
    urlSlug: 'slim-fit-chino-trousers', keywords: 'chinos, trousers',
    status: 'published', featured: false, bestSeller: false, unitsSold: 132, revenue: 263868, rating: 4.2, reviewCount: 40,
    createdAt: '2026-02-10',
  },
  {
    id: 'prod-008', name: 'Wrap Midi Dress', sku: 'CLT-DRS-008',
    description: 'A flowing wrap midi dress in a soft viscose blend, finished with a self-tie waist belt.',
    shortDescription: 'Viscose blend wrap midi dress.',
    brandId: 'brand-noir-label', categoryId: 'cat-dresses', collectionIds: ['col-summer', 'col-new-arrivals'],
    tags: ['dress', 'midi', 'wrap'],
    price: 3199, salePrice: null, costPrice: 1400, tax: 5, discount: 0,
    stock: 37, lowStockThreshold: 10, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-008', 700, 900), thumbnail: placeholderImage('prod-008-thumb', 200, 200), gallery: gallery('prod-008'),
    variants: variants('CLT-DRS-008', ['XS', 'S', 'M', 'L'], ['Black', 'Blue'], 3199),
    metaTitle: 'Wrap Midi Dress | Clotchy', metaDescription: 'Flowing wrap midi dress.',
    urlSlug: 'wrap-midi-dress', keywords: 'midi dress, wrap dress',
    status: 'published', featured: true, bestSeller: false, unitsSold: 96, revenue: 307104, rating: 4.6, reviewCount: 33,
    createdAt: '2026-02-14',
  },
  {
    id: 'prod-009', name: 'Structured Tote Bag', sku: 'CLT-ACC-009',
    description: 'A structured vegan-leather tote with an interior laptop sleeve and magnetic closure.',
    shortDescription: 'Structured vegan-leather tote.',
    brandId: 'brand-clotchy-originals', categoryId: 'cat-accessories', collectionIds: ['col-premium'],
    tags: ['bag', 'tote', 'accessory'],
    price: 3499, salePrice: null, costPrice: 1600, tax: 5, discount: 0,
    stock: 22, lowStockThreshold: 8, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-009', 700, 900), thumbnail: placeholderImage('prod-009-thumb', 200, 200), gallery: gallery('prod-009'),
    variants: variants('CLT-ACC-009', ['One Size'], ['Black', 'Beige'], 3499),
    metaTitle: 'Structured Tote Bag | Clotchy', metaDescription: 'Structured vegan-leather tote bag.',
    urlSlug: 'structured-tote-bag', keywords: 'tote bag, accessories',
    status: 'published', featured: false, bestSeller: false, unitsSold: 61, revenue: 213439, rating: 4.4, reviewCount: 19,
    createdAt: '2026-01-30',
  },
  {
    id: 'prod-010', name: 'Court Leather Sneakers', sku: 'CLT-FTW-010',
    description: 'Minimalist court sneakers in full-grain leather with a cupsole and perforated toe box for breathability.',
    shortDescription: 'Full-grain leather court sneakers.',
    brandId: 'brand-urban-edge', categoryId: 'cat-footwear', collectionIds: ['col-trending', 'col-new-arrivals'],
    tags: ['sneakers', 'leather', 'footwear'],
    price: 4999, salePrice: 4249, costPrice: 2300, tax: 5, discount: 15,
    stock: 0, lowStockThreshold: 10, availability: 'out-of-stock', allowBackorder: true,
    mainImage: placeholderImage('prod-010', 700, 900), thumbnail: placeholderImage('prod-010-thumb', 200, 200), gallery: gallery('prod-010'),
    variants: variants('CLT-FTW-010', ['7', '8', '9', '10', '11'], ['White', 'Black'], 4249, 0),
    metaTitle: 'Court Leather Sneakers | Clotchy', metaDescription: 'Minimalist full-grain leather sneakers.',
    urlSlug: 'court-leather-sneakers', keywords: 'sneakers, leather shoes',
    status: 'out-of-stock', featured: true, bestSeller: true, unitsSold: 389, revenue: 1652861, rating: 4.8, reviewCount: 172,
    createdAt: '2025-12-05',
  },
  {
    id: 'prod-011', name: 'Ribbed Knit Polo', sku: 'CLT-TSH-011',
    description: 'A ribbed knit polo shirt with mother-of-pearl buttons and a soft, stretchy hand-feel.',
    shortDescription: 'Ribbed stretch knit polo.',
    brandId: 'brand-clotchy-originals', categoryId: 'cat-tshirts', collectionIds: ['col-summer'],
    tags: ['polo', 'knit'],
    price: 1899, salePrice: null, costPrice: 850, tax: 5, discount: 0,
    stock: 48, lowStockThreshold: 10, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-011', 700, 900), thumbnail: placeholderImage('prod-011-thumb', 200, 200), gallery: gallery('prod-011'),
    variants: variants('CLT-TSH-011', ['S', 'M', 'L', 'XL'], ['Navy', 'White'], 1899),
    metaTitle: 'Ribbed Knit Polo | Clotchy', metaDescription: 'Ribbed stretch knit polo shirt.',
    urlSlug: 'ribbed-knit-polo', keywords: 'polo shirt, knit polo',
    status: 'published', featured: false, bestSeller: false, unitsSold: 88, revenue: 167112, rating: 4.1, reviewCount: 22,
    createdAt: '2026-02-20',
  },
  {
    id: 'prod-012', name: 'Distressed Denim Jacket', sku: 'CLT-JKT-012',
    description: 'A classic trucker-style denim jacket with light distressing and a button-through front.',
    shortDescription: 'Distressed trucker denim jacket.',
    brandId: 'brand-denim-co', categoryId: 'cat-jackets', collectionIds: ['col-streetwear', 'col-trending'],
    tags: ['denim', 'jacket'],
    price: 3799, salePrice: 3299, costPrice: 1700, tax: 5, discount: 13,
    stock: 9, lowStockThreshold: 10, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-012', 700, 900), thumbnail: placeholderImage('prod-012-thumb', 200, 200), gallery: gallery('prod-012'),
    variants: variants('CLT-JKT-012', ['S', 'M', 'L', 'XL'], ['Blue'], 3299),
    metaTitle: 'Distressed Denim Jacket | Clotchy', metaDescription: 'Classic distressed denim jacket.',
    urlSlug: 'distressed-denim-jacket', keywords: 'denim jacket, trucker jacket',
    status: 'published', featured: false, bestSeller: false, unitsSold: 67, revenue: 220983, rating: 4.3, reviewCount: 27,
    createdAt: '2026-01-08',
  },
  {
    id: 'prod-013', name: 'Cargo Utility Trousers', sku: 'CLT-TRS-013',
    description: 'Six-pocket cargo trousers in a durable ripstop cotton blend with an adjustable drawcord hem.',
    shortDescription: 'Ripstop cotton cargo trousers.',
    brandId: 'brand-urban-edge', categoryId: 'cat-jeans', collectionIds: ['col-streetwear'],
    tags: ['cargo', 'utility'],
    price: 2699, salePrice: null, costPrice: 1150, tax: 5, discount: 0,
    stock: 54, lowStockThreshold: 10, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-013', 700, 900), thumbnail: placeholderImage('prod-013-thumb', 200, 200), gallery: gallery('prod-013'),
    variants: variants('CLT-TRS-013', ['30', '32', '34', '36'], ['Black', 'Olive'], 2699),
    metaTitle: 'Cargo Utility Trousers | Clotchy', metaDescription: 'Six-pocket ripstop cargo trousers.',
    urlSlug: 'cargo-utility-trousers', keywords: 'cargo trousers, utility pants',
    status: 'published', featured: false, bestSeller: false, unitsSold: 145, revenue: 391355, rating: 4.4, reviewCount: 45,
    createdAt: '2026-01-22',
  },
  {
    id: 'prod-014', name: 'Satin Slip Dress', sku: 'CLT-DRS-014',
    description: 'A bias-cut satin slip dress with adjustable straps and a subtle cowl neckline.',
    shortDescription: 'Bias-cut satin slip dress.',
    brandId: 'brand-noir-label', categoryId: 'cat-dresses', collectionIds: ['col-premium', 'col-trending'],
    tags: ['dress', 'satin'],
    price: 3599, salePrice: 2999, costPrice: 1600, tax: 5, discount: 17,
    stock: 18, lowStockThreshold: 8, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-014', 700, 900), thumbnail: placeholderImage('prod-014-thumb', 200, 200), gallery: gallery('prod-014'),
    variants: variants('CLT-DRS-014', ['XS', 'S', 'M', 'L'], ['Black', 'Beige'], 2999),
    metaTitle: 'Satin Slip Dress | Clotchy', metaDescription: 'Bias-cut satin slip dress.',
    urlSlug: 'satin-slip-dress', keywords: 'slip dress, satin dress',
    status: 'published', featured: true, bestSeller: false, unitsSold: 79, revenue: 236921, rating: 4.7, reviewCount: 29,
    createdAt: '2026-02-18',
  },
  {
    id: 'prod-015', name: 'Canvas High-Top Sneakers', sku: 'CLT-FTW-015',
    description: 'Classic canvas high-top sneakers with a vulcanized rubber sole and reinforced toe cap.',
    shortDescription: 'Canvas high-top sneakers.',
    brandId: 'brand-urban-edge', categoryId: 'cat-footwear', collectionIds: ['col-streetwear', 'col-summer'],
    tags: ['sneakers', 'canvas'],
    price: 2299, salePrice: null, costPrice: 1000, tax: 5, discount: 0,
    stock: 7, lowStockThreshold: 10, availability: 'in-stock', allowBackorder: true,
    mainImage: placeholderImage('prod-015', 700, 900), thumbnail: placeholderImage('prod-015-thumb', 200, 200), gallery: gallery('prod-015'),
    variants: variants('CLT-FTW-015', ['7', '8', '9', '10'], ['Black', 'White', 'Red'], 2299),
    metaTitle: 'Canvas High-Top Sneakers | Clotchy', metaDescription: 'Classic canvas high-top sneakers.',
    urlSlug: 'canvas-high-top-sneakers', keywords: 'canvas sneakers, high-top shoes',
    status: 'published', featured: false, bestSeller: true, unitsSold: 224, revenue: 514976, rating: 4.5, reviewCount: 81,
    createdAt: '2026-01-14',
  },
  {
    id: 'prod-016', name: 'Leather Belt', sku: 'CLT-ACC-016',
    description: 'A full-grain leather belt with a brushed metal buckle, hand-finished edges.',
    shortDescription: 'Full-grain leather belt.',
    brandId: 'brand-clotchy-originals', categoryId: 'cat-accessories', collectionIds: ['col-premium'],
    tags: ['belt', 'leather'],
    price: 1299, salePrice: null, costPrice: 550, tax: 5, discount: 0,
    stock: 3, lowStockThreshold: 10, availability: 'in-stock', allowBackorder: false,
    mainImage: placeholderImage('prod-016', 700, 900), thumbnail: placeholderImage('prod-016-thumb', 200, 200), gallery: gallery('prod-016'),
    variants: variants('CLT-ACC-016', ['32', '34', '36', '38'], ['Black', 'Brown'], 1299),
    metaTitle: 'Leather Belt | Clotchy', metaDescription: 'Full-grain leather belt.',
    urlSlug: 'leather-belt', keywords: 'leather belt, accessories',
    status: 'draft', featured: false, bestSeller: false, unitsSold: 34, revenue: 44166, rating: 4.0, reviewCount: 11,
    createdAt: '2026-02-25',
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS_MOCK.find(p => p.id === id);
}
